const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
const briefURL = entry => `/entries/${entry.slug}/`;
const list = items => `<ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`;
const sourceLinks = entry => `<p class="citation">${esc(entry.citation)}</p><p><a href="${esc(entry.primarySource)}">Primary source</a> · <a href="${briefURL(entry)}">Full brief</a></p>`;
const modality = row => row.platform.includes('PET') ? 'PET' : row.specimen.toLowerCase().includes('csf') ? 'CSF' : 'Blood';
export const assayId = row => row.id || row.assay.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const normalize = value => value.toLowerCase().replace(/[^a-z0-9]/g,'');

export function relatedBriefs(row, entries) {
  const explicit = row.relatedBriefs || [];
  const ids = new Set(explicit.map(link=>link.id));
  const exact = entries.filter(entry=>!ids.has(entry.id) && entry.assays.some(assay=>normalize(assay)===normalize(row.assay)))
    .map(entry=>({id:entry.id,relationship:'Related brief'}));
  return [...explicit,...exact].map(link=>({...link,entry:entries.find(entry=>entry.id===link.id)})).filter(link=>link.entry);
}

const relatedList = links => links.length ? `<ul class="related-briefs">${links.map(({entry,relationship})=>`<li><a href="${briefURL(entry)}">${esc(entry.title)}</a><small>${esc(relationship)} · ${date(entry.sourceDate)}</small></li>`).join('')}</ul>` : '<p class="muted">No related brief in the current archive.</p>';
const policyField = (value, fallback) => value?.text ? `<p>${esc(value.text)}</p><small>Verified ${date(value.verified)} · <a href="${esc(value.source)}">Policy source</a></small>` : `<span class="muted">${fallback} No verification date recorded.</span>`;

export function landscapeView(landscape, entries) {
  const rows = landscape.map(row=>({...row,id:assayId(row),links:relatedBriefs(row,entries)}));
  const options = rows.map(row=>`<option value="${esc(row.id)}">${esc(row.assay)}</option>`).join('');
  const attributes = row => `data-landscape-row data-modality="${modality(row).toLowerCase()}" data-search="${esc(Object.values(row).filter(value=>typeof value==='string').join(' ').toLowerCase())}"`;
  const tableRows = rows.map(row=>`<tr ${attributes(row)}><td><strong>${esc(row.assay)}</strong><br>${esc(row.biomarker)}</td><td>${esc(row.manufacturer)}</td><td>${esc(row.specimen)}<br>${esc(row.platform)}</td><td>${esc(row.intendedUse)}</td><td>${esc(row.regulatoryStatus)}<br><small>${esc(row.availability)}</small></td><td>${esc(row.threshold)}</td><td>${esc(row.reference)}</td><td><a href="${esc(row.source)}">Source</a><br>${date(row.verified)}<details class="related-disclosure"><summary>Related briefs (${row.links.length})</summary>${relatedList(row.links)}</details></td></tr>`).join('');
  const cards = rows.map(row=>`<article class="landscape-card" ${attributes(row)}><h3>${esc(row.assay)}</h3><p>${esc(row.biomarker)} · ${esc(row.manufacturer)}</p><dl>${[['Specimen / platform',`${row.specimen}; ${row.platform}`],['Intended use',row.intendedUse],['Regulatory status',row.regulatoryStatus],['Availability',row.availability],['Threshold',row.threshold],['Reference',row.reference],['Last verified',date(row.verified)]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><a href="${esc(row.source)}">Validation source</a><details class="related-disclosure"><summary>Related briefs (${row.links.length})</summary>${relatedList(row.links)}</details></article>`).join('');
  const fields = [
    ['Biomarker',row=>esc(row.biomarker)],['Maker / laboratory',row=>esc(row.manufacturer)],
    ['Intended use / population',row=>esc(row.intendedUse)],['Specimen',row=>esc(row.specimen)],
    ['Platform',row=>esc(row.platform)],['Threshold / interpretation',row=>esc(row.threshold)],
    ['Reference standard',row=>esc(row.reference)],['Regulatory authorization',row=>esc(row.regulatoryStatus)],
    ['Availability',row=>esc(row.availability)],
    ['Coverage',row=>policyField(row.coverage,'Unknown. No payer-specific determination recorded.')],
    ['Reimbursement / patient cost',row=>policyField(row.reimbursement,'Unknown. No verified payment or patient-cost estimate recorded.')],
    ['Verification',row=>`<a href="${esc(row.source)}">Primary reference</a><br>${date(row.verified)}<p>${esc(row.verification)}</p>`],
    ['Related briefs',row=>relatedList(row.links)]
  ];
  const comparison = `<section class="comparison-controls" aria-labelledby="compare-heading"><h2 id="compare-heading">Compare tests</h2><p>Choose two or three tests. Each status retains its source and verification date.</p><div class="comparison-selects">${['First test','Second test','Third test (optional)'].map((label,index)=>`<label class="field"><span>${label}</span><select data-comparison-select aria-label="${label}"><option value="">Select a test</option>${options}</select></label>`).join('')}</div><div class="selection-actions"><p data-comparison-message role="status">Choose at least two tests to compare.</p><button type="button" data-clear-comparison disabled>Clear comparison</button></div><noscript><p>Enable JavaScript to compare selected tests. The full landscape remains available below.</p></noscript></section>
  <section data-comparison-result hidden aria-labelledby="comparison-heading"><h2 id="comparison-heading">Selected tests</h2><p class="comparison-note">Performance estimates belong to their study populations and reference standards. This comparison does not rank tests. Coverage and payment require separate verification.</p><div class="comparison-scroll" role="region" aria-label="Selected test comparison; scroll horizontally on smaller screens" tabindex="0"><table class="comparison-table"><caption class="visually-hidden">Test characteristics and dated sources</caption><thead><tr><th scope="col">Characteristic</th>${rows.map(row=>`<th scope="col" data-compare-id="${esc(row.id)}" hidden>${esc(row.assay)}</th>`).join('')}</tr></thead><tbody>${fields.map(([label,render])=>`<tr><th scope="row">${label}</th>${rows.map(row=>`<td data-compare-id="${esc(row.id)}" hidden>${render(row)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;
  const linkedEntries = entries.filter(entry=>rows.some(row=>row.links.some(link=>link.id===entry.id)));
  const context = `<section data-comparison-evidence hidden aria-labelledby="evidence-context-heading"><h2 id="evidence-context-heading">Evidence context</h2><p>Results remain attached to the original population, design, and source. Studies of an assay component or related assay are labeled separately.</p>${linkedEntries.map(entry=>{
    const associations=rows.flatMap(row=>row.links.filter(link=>link.id===entry.id).map(link=>({id:row.id,name:row.assay,relationship:link.relationship})));
    return `<details class="evidence-context" data-evidence-for="${esc(associations.map(row=>row.id).join('|'))}" hidden><summary>${esc(entry.title)}</summary><div class="evidence-context-body">${associations.map(row=>`<p class="context-association" data-evidence-assay="${esc(row.id)}"><strong>${esc(row.name)}</strong> · ${esc(row.relationship)}</p>`).join('')}<p class="muted">${esc(entry.evidenceSource)} · ${date(entry.sourceDate)}</p><h3>Population and design</h3><p>${esc(entry.studyDesign)}</p><h3>Key results</h3>${list(entry.keyResults)}<h3>Limitations</h3>${list(entry.limitations)}${sourceLinks(entry)}</div></details>`;
  }).join('')}<p class="muted" data-no-comparison-evidence hidden>No related briefs for these tests are currently in the archive. Use the dated primary references above.</p></section>`;
  return `<header class="page-head"><p class="eyebrow">Assay and testing landscape</p><h1>What is available, authorized, or still research-only</h1><p>This table does not rank assays. Cross-study accuracy estimates are not treated as head-to-head evidence.</p></header>${comparison}${context}<h2>Complete landscape</h2><div class="tool-row"><label class="field"><span>Search landscape</span><input class="search-input" type="search" data-landscape-search placeholder="Assay, marker, platform…"></label><label class="field"><span>Modality</span><select data-landscape-filter><option value="">All</option><option>Blood</option><option>CSF</option><option>PET</option></select></label></div><p class="callout">Unknown, research-use-only, company-reported, and rollout-pending states are stated explicitly. Every regulatory and availability field has a verification date.</p><div class="landscape-wrap"><table class="landscape-table"><thead><tr><th>Assay / biomarker</th><th>Maker / lab</th><th>Specimen / platform</th><th>Intended use</th><th>Status / availability</th><th>Threshold</th><th>Reference</th><th>Verified source / briefs</th></tr></thead><tbody>${tableRows}</tbody></table></div><div class="landscape-cards">${cards}</div>`;
}

export function meetingView(entries) {
  return `<header class="page-head meeting-page-head"><p class="eyebrow">Meeting preparation</p><h1>Your selected briefs</h1><p>Build a packet from the archive using “Add to meeting”. The packet keeps the findings, limitations, questions, and primary sources together.</p></header><section class="meeting-toolbar" aria-label="Packet controls"><p data-meeting-count role="status">No briefs selected</p><div class="selection-actions"><button type="button" class="primary-button" data-print-meeting disabled>Print / save PDF</button><button type="button" data-copy-meeting disabled>Copy packet link</button><button type="button" data-clear-meeting disabled>Clear packet</button><a class="button-link" href="/archive/">Browse archive</a></div><p class="muted">Selections are saved in this browser. A packet link opens the same selection on another device. Briefs reflect the current archive when opened.</p><p data-meeting-notice role="status"></p></section><noscript><p>Enable JavaScript to select and print a packet. Individual briefs remain available in the <a href="/archive/">archive</a>.</p></noscript><p class="meeting-empty" data-meeting-empty>No briefs selected. <a href="/archive/">Choose briefs from the archive.</a></p><section class="meeting-packet" data-meeting-packet hidden aria-label="Selected evidence packet"><header class="packet-header"><h2>AD Biomarker Field Brief</h2><p>Meeting packet · <span data-packet-date></span></p></header>${entries.map(entry=>`<article class="packet-brief" data-packet-id="${esc(entry.id)}" hidden><header><p class="packet-meta">${esc(entry.relevance)} · ${esc(entry.evidenceSource)} · ${date(entry.sourceDate)}</p><h2>${esc(entry.title)}</h2><p>${esc(entry.bottomLine)}</p><button type="button" data-remove-meeting="${esc(entry.id)}" aria-label="Remove ${esc(entry.title)} from meeting">Remove from packet</button></header><h3>Population and design</h3><p>${esc(entry.studyDesign)}</p><h3>Key findings</h3>${list(entry.keyResults)}<h3>Limitations</h3>${list(entry.limitations)}<h3>Likely questions</h3><dl>${entry.questions.map(item=>`<div class="packet-question"><dt>${esc(item.q)}</dt><dd>${esc(item.a)}</dd></div>`).join('')}</dl>${sourceLinks(entry)}${entry.corrections?.length?`<h3>Correction notes</h3>${list(entry.corrections)}`:''}</article>`).join('')}<p class="packet-disclosure">Compiled from the current AD Biomarker Field Brief archive. AI assists discovery and drafting; confirm findings against the primary sources. This independent resource does not represent Quanterix and is not promotional communication.</p></section>`;
}
